name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Grant execute permission for gradlew
        run: |
          cd iraq_stations_app/android
          chmod +x gradlew || true

      - name: Configure Gradle properties
        run: |
          echo "android.newDsl=false" >> iraq_stations_app/android/gradle.properties

      - name: Get dependencies
        run: |
          cd iraq_stations_app
          flutter pub get

      - name: Build APK
        run: |
          cd iraq_stations_app
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: iraq_stations_app/build/app/outputs/flutter-apk/app-release.apk
