name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Grant execute permission for gradlew
        run: |
          find . -name gradlew -exec chmod +x {} \;

      - name: Get dependencies
        run: |
          cd iraq_stations_app
          flutter pub get

      - name: Build APK with detailed logs
        run: |
          cd iraq_stations_app
          flutter build apk --release --verbose --no-tree-shake-icons
